/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica;

/**
 *
 * @author marti
 */
public class Menu extends javax.swing.JFrame {
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmAgendarCita = new javax.swing.JMenu();
        opOftamologia = new javax.swing.JMenuItem();
        opMedicinaInterna = new javax.swing.JMenuItem();
        opCardio = new javax.swing.JMenuItem();
        opNeurologia = new javax.swing.JMenuItem();
        opPediatria = new javax.swing.JMenuItem();
        opObtsetrecia = new javax.swing.JMenuItem();
        jmComprarFarmacos = new javax.swing.JMenu();
        opAcetaminofen = new javax.swing.JMenuItem();
        opSevedol = new javax.swing.JMenuItem();
        opAdvil = new javax.swing.JMenuItem();
        opGotasoftalmologícas = new javax.swing.JMenuItem();
        opLosartan = new javax.swing.JMenuItem();
        opFentanilo = new javax.swing.JMenuItem();
        jmDiagnostico = new javax.swing.JMenu();
        opDiagOfta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setName("ClinicaMalitas"); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agendar, Modificaciones, Informes, Pacientes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("CLINICA MALITAS");

        jLabel7.setText("🏥");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("!Bienvenido¡");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/saladeespera.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Hola somos Clinicas Malitas!, y estamos aqui para servirte");

        jLabel14.setText("Contacto:");

        jLabel15.setText("+57 312524157");

        jLabel16.setText("@FacebookCLINICASMALITAS");

        jLabel17.setText("@instagramCLINICAS_MALITAS");

        jLabel18.setText("@XCLINICAS_MALITAS");

        jLabel19.setText("Somos una empresa destinada a servir para primar por su salud y bienestar");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/logoblnaco.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))))
                            .addComponent(jLabel15)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(0, 0, 0)
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addComponent(jLabel18)
                .addGap(18, 18, 18))
        );

        escritorio.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 255));

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jmAgendarCita.setText("Agendar Cita");

        opOftamologia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opOftamologia.setText("Oftamologia");
        opOftamologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opOftamologiaActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opOftamologia);

        opMedicinaInterna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opMedicinaInterna.setText("Medicina Interna");
        opMedicinaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMedicinaInternaActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opMedicinaInterna);

        opCardio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opCardio.setText("Cardiologia");
        opCardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCardioActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opCardio);

        opNeurologia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opNeurologia.setText("Neurologia");
        opNeurologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNeurologiaActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opNeurologia);

        opPediatria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opPediatria.setText("Pediatria");
        opPediatria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPediatriaActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opPediatria);

        opObtsetrecia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opObtsetrecia.setText("Obtsetrecia");
        opObtsetrecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opObtsetreciaActionPerformed(evt);
            }
        });
        jmAgendarCita.add(opObtsetrecia);

        jMenuBar1.add(jmAgendarCita);

        jmComprarFarmacos.setText("Comprar Farmacos");

        opAcetaminofen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opAcetaminofen.setText("Acetaminofen");
        opAcetaminofen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAcetaminofenActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opAcetaminofen);

        opSevedol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opSevedol.setText("Sevedol");
        opSevedol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSevedolActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opSevedol);

        opAdvil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opAdvil.setText("Advil");
        opAdvil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAdvilActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opAdvil);

        opGotasoftalmologícas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opGotasoftalmologícas.setText("Gotas Oftalmologícas");
        opGotasoftalmologícas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opGotasoftalmologícasActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opGotasoftalmologícas);

        opLosartan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opLosartan.setText("Losartan");
        opLosartan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLosartanActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opLosartan);

        opFentanilo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opFentanilo.setText("Fentanilo");
        opFentanilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opFentaniloActionPerformed(evt);
            }
        });
        jmComprarFarmacos.add(opFentanilo);

        jMenuBar1.add(jmComprarFarmacos);

        jmDiagnostico.setText("Diagnostico");

        opDiagOfta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opDiagOfta.setText("Diagnosticos Generales");
        opDiagOfta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDiagOftaActionPerformed(evt);
            }
        });
        jmDiagnostico.add(opDiagOfta);

        jMenuBar1.add(jmDiagnostico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opOftamologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opOftamologiaActionPerformed
        // TODO add your handling code here:
        Oftamologia verventana=new Oftamologia();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opOftamologiaActionPerformed

    private void opObtsetreciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opObtsetreciaActionPerformed
        // TODO add your handling code here:
        Obtsetrecia verventana=new Obtsetrecia();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opObtsetreciaActionPerformed

    private void opMedicinaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMedicinaInternaActionPerformed
        // TODO add your handling code here:
        MedicinaInterna verventana=new MedicinaInterna();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opMedicinaInternaActionPerformed

    private void opCardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCardioActionPerformed
        // TODO add your handling code here:
        Cardiologia verventana=new Cardiologia();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opCardioActionPerformed

    private void opNeurologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNeurologiaActionPerformed
        // TODO add your handling code here:
        Neurologia verventana=new Neurologia();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opNeurologiaActionPerformed

    private void opPediatriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPediatriaActionPerformed
        // TODO add your handling code here:
        Pediatria verventana=new Pediatria();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opPediatriaActionPerformed

    private void opSevedolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSevedolActionPerformed
        // TODO add your handling code here:
        Sevedol verventana=new Sevedol();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opSevedolActionPerformed

    private void opLosartanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLosartanActionPerformed
        // TODO add your handling code here:
        Losartan verventana=new Losartan();
        escritorio.add(verventana);
        verventana.show();
        
    }//GEN-LAST:event_opLosartanActionPerformed

    private void opAcetaminofenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAcetaminofenActionPerformed
        // TODO add your handling code here:
        Acetaminofen verventana=new Acetaminofen();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opAcetaminofenActionPerformed

    private void opAdvilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAdvilActionPerformed
        // TODO add your handling code here:
        Advil verventana=new Advil();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opAdvilActionPerformed

    private void opGotasoftalmologícasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opGotasoftalmologícasActionPerformed
        // TODO add your handling code here:
        GotasOftomologicas verventana=new GotasOftomologicas();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opGotasoftalmologícasActionPerformed

    private void opFentaniloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opFentaniloActionPerformed
        // TODO add your handling code here:
        Fentanilo verventana=new Fentanilo();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opFentaniloActionPerformed

    private void opDiagOftaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDiagOftaActionPerformed
        // TODO add your handling code here:
        Diagnosticos verventana=new Diagnosticos();
        escritorio.add(verventana);
        verventana.show();
        
    }//GEN-LAST:event_opDiagOftaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JMenu jmAgendarCita;
    private javax.swing.JMenu jmComprarFarmacos;
    private javax.swing.JMenu jmDiagnostico;
    private javax.swing.JMenuItem opAcetaminofen;
    private javax.swing.JMenuItem opAdvil;
    private javax.swing.JMenuItem opCardio;
    private javax.swing.JMenuItem opDiagOfta;
    private javax.swing.JMenuItem opFentanilo;
    private javax.swing.JMenuItem opGotasoftalmologícas;
    private javax.swing.JMenuItem opLosartan;
    private javax.swing.JMenuItem opMedicinaInterna;
    private javax.swing.JMenuItem opNeurologia;
    private javax.swing.JMenuItem opObtsetrecia;
    private javax.swing.JMenuItem opOftamologia;
    private javax.swing.JMenuItem opPediatria;
    private javax.swing.JMenuItem opSevedol;
    // End of variables declaration//GEN-END:variables
}
